---
- hosts: all
  user: vagrant
  tasks:
  - name: Update APT package cache
    apt: update_cache=yes
  - name: Installing required packages
    action: apt name={{item}}
    with_items:
      - git
      - nodejs

- include: ansible/postgres.yml

- hosts: all
  vars:
    ruby: ruby-2.0.0-p247
    project_path: /vagrant
  user: vagrant
  sudo: no
  tasks:
  - include: ansible/say_hello.yml
  - include: ansible/ruby.yml
  - name: Install Bundler
    shell: bash -lc "gem install bundler"
  - name: Install application gems
    shell: bash -lc "bundle install" chdir={{ project_path }}
  - name: Install DB
    shell: bash -lc "foreman run rake db:setup" chdir={{ project_path }}
  - name: Register Upstart
    sudo: yes
    tasks:
    - name: Install Foreman for sudoer
      shell: bash -lc "gem install foreman"
    - name: Export Foreman init scripts
      shell: bash -lc "foreman export --app buddy --user vagrant upstart /etc/init" chdir={{ project_path }}
  - name: Start Foreman
    shell: bash -lc "start buddy" chdir={{ project_path }}
