development:
  adapter: postgresql
  encoding: unicode
  database: snatch_development
  pool: 5
  user: red
  password: z
  host: localhost

test:
  adapter: postgresql
  encoding: unicode
  database: snatch_test
  pool: 5
  user: red
  password: z
  host: localhost
