defaults: &defaults
  enabled: yes
  url: 'http://localhost:9200'

development:
  <<: *defaults

production:
  url: 'http://0.1.2.3:9200'

staging:
  url: 'http://0.1.2.3:9200'

test:
  enabled: yes
  <<: *defaults

