# Here are the settings that are common to all environments
common: &default_settings
  license_key: '57d3d86c0adc3653e113e6bece0d129ad43e9127'
  agent_enabled: auto

  app_name: Connectpal
  monitor_mode: true
  developer_mode: false
  log_level: info
  # ssl: false

  browser_monitoring:
    auto_instrument: true

  # proxy_host: hostname
  # proxy_port: 8080
  # proxy_user:
  # proxy_pass:

  audit_log:
    enabled: false

  capture_params: true

  transaction_tracer:
    enabled: true
    transaction_threshold: apdex_f
    record_sql: obfuscated
    stack_trace_threshold: 0.500
    # explain_enabled: true
    # explain_threshold: 0.5

  error_collector:
    enabled: true
    capture_source: true
    ignore_errors: "ActionController::RoutingError,Sinatra::NotFound"

  # capture_memcache_keys: true

development:
  <<: *default_settings
  monitor_mode: false
  developer_mode: true
  # textmate: true

test:
  <<: *default_settings
  monitor_mode: false

production:
  <<: *default_settings
  monitor_mode: true

staging:
  <<: *default_settings
  agent_enabled: false
  monitor_mode: false
  app_name: Connectpal (Staging)
